Repository BoeingMerryHo/kbo-ticketing-platform, pull requests merged in 2025-04, with the labels that each got.

#3 [Docs] : PR & Issue template 생성
  .github/ISSUE_TEMPLATE/boeingmerryho-s-issue-template.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 📃 docs, ⚙️ setting

#7 [Config] : Config Server 초기 설정
  config-service/.gitattributes
  config-service/build.gradle
  config-service/gradle/wrapper/gradle-wrapper.jar
  config-service/gradle/wrapper/gradle-wrapper.properties
  config-service/settings.gradle
  config-service/src/main/java/com/boeingmerryho/infrastructure/config_service/ConfigServiceApplication.java
  config-service/src/test/java/com/boeingmerryho/infrastructure/config_service/ConfigServiceApplicationTests.java
Labels: ✏️ feat, ⚙️ setting

#9 [Gateway] : gateway-service init
  gateway-service/.gitattributes
  gateway-service/.gitignore
  gateway-service/build.gradle
  gateway-service/gradle/wrapper/gradle-wrapper.jar
  gateway-service/gradle/wrapper/gradle-wrapper.properties
  gateway-service/settings.gradle
  gateway-service/src/main/java/com/boeingmerryho/infrastructure/gatewayservice/GatewayServiceApplication.java
  gateway-service/src/main/java/com/boeingmerryho/infrastructure/gatewayservice/config/CorsGlobalConfig.java
  gateway-service/src/main/java/com/boeingmerryho/infrastructure/gatewayservice/config/RedisConfig.java
  gateway-service/src/main/java/com/boeingmerryho/infrastructure/gatewayservice/exception/ErrorCode.java
  gateway-service/src/main/java/com/boeingmerryho/infrastructure/gatewayservice/exception/GatewayException.java
  gateway-service/src/main/java/com/boeingmerryho/infrastructure/gatewayservice/exception/GlobalExceptionHandler.java
  gateway-service/src/main/java/com/boeingmerryho/infrastructure/gatewayservice/filter/JwtAuthFilter.java
  gateway-service/src/test/java/com/boeingmerryho/infrastructure/gatewayservice/GatewayServiceApplicationTests.java
  settings.gradle
Labels: ✏️ feat

#10 [Eureka] : Eureka service add
  .gitignore
  build.gradle
  eureka-service/.gitattributes
  eureka-service/build.gradle
  eureka-service/gradle/wrapper/gradle-wrapper.jar
  eureka-service/gradle/wrapper/gradle-wrapper.properties
  eureka-service/settings.gradle
  eureka-service/src/main/java/com/boeingmerryho/infrastructure/eurekaservice/EurekaServiceApplication.java
  eureka-service/src/main/resources/application.yml
  eureka-service/src/main/resources/db/migration/V10__create_seat.sql
  eureka-service/src/main/resources/db/migration/V11__create_seat_reservation.sql
  eureka-service/src/main/resources/db/migration/V12__create_payment.sql
  eureka-service/src/main/resources/db/migration/V13__create_detail.sql
  eureka-service/src/main/resources/db/migration/V14__create_payment_ticket.sql
  eureka-service/src/main/resources/db/migration/V15__create_payment_membership.sql
  eureka-service/src/main/resources/db/migration/V16__create_store.sql
  eureka-service/src/main/resources/db/migration/V17__create_queue.sql
  eureka-service/src/main/resources/db/migration/V18__create_notification.sql
  eureka-service/src/main/resources/db/migration/V19__insert_user.sql
  eureka-service/src/main/resources/db/migration/V1__init.sql
  eureka-service/src/main/resources/db/migration/V20__insert_membership.sql
  eureka-service/src/main/resources/db/migration/V21__insert_membership_user.sql
  eureka-service/src/main/resources/db/migration/V22__insert_stadium.sql
  eureka-service/src/main/resources/db/migration/V23__insert_team.sql
  eureka-service/src/main/resources/db/migration/V24__insert_match.sql
  eureka-service/src/main/resources/db/migration/V25__insert_seat.sql
  eureka-service/src/main/resources/db/migration/V2__create_user.sql
  eureka-service/src/main/resources/db/migration/V3__create_membership.sql
  eureka-service/src/main/resources/db/migration/V4__create_membership_user.sql
  eureka-service/src/main/resources/db/migration/V5__create_ticket.sql
  eureka-service/src/main/resources/db/migration/V6__create_ticket_history.sql
  eureka-service/src/main/resources/db/migration/V7__create_match.sql
  eureka-service/src/main/resources/db/migration/V8__create_stadium.sql
  eureka-service/src/main/resources/db/migration/V9__create_team.sql
  eureka-service/src/test/java/com/boeingmerryho/infrastructure/eurekaservice/EurekaServiceApplicationTests.java
  settings.gradle
Labels: ✏️ feat

#16 [Seat] : 프로젝트 세팅 #14
  .gitignore
  seat-service/.gitattributes
  seat-service/build.gradle
  seat-service/gradle/wrapper/gradle-wrapper.jar
  seat-service/gradle/wrapper/gradle-wrapper.properties
  seat-service/settings.gradle
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/SeatServiceApplication.java
  seat-service/src/main/resources/application.yaml
  seat-service/src/main/resources/logback.xml
  seat-service/src/test/java/com/boeingmerryho/business/seatservice/SeatServiceApplicationTests.java
Labels: ⚙️ setting

#22 [Seat] : Seat Settings
  seat-service/build.gradle
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/application/dto/mapper/SeatApplicationMapper.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/application/service/SeatAdminService.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/application/service/SeatService.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/domain/BaseEntity.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/domain/Seat.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/domain/SeatReservation.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/infrastructure/SeatRepository.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/presentation/controller/SeatAdminController.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/presentation/controller/SeatController.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/presentation/dto/mapper/SeatPresentationMapper.java
Labels: ⚙️ setting

#29 [Ticket] : Ticket Service Init
  ticket-service/.gitattributes
  ticket-service/build.gradle
  ticket-service/gradle/wrapper/gradle-wrapper.jar
  ticket-service/gradle/wrapper/gradle-wrapper.properties
  ticket-service/settings.gradle
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/TicketServiceApplication.java
  ticket-service/src/main/resources/application.yml
  ticket-service/src/test/java/com/boeingmerryho/business/ticketservice/TicketServiceApplicationTests.java
Labels: ⚙️ setting

#23 [Seat] : Seat Settings
  seat-service/build.gradle
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/application/dto/mapper/SeatApplicationMapper.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/application/service/SeatAdminService.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/application/service/SeatService.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/domain/BaseEntity.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/domain/Seat.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/domain/SeatReservation.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/infrastructure/SeatRepository.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/presentation/controller/SeatAdminController.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/presentation/controller/SeatController.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/presentation/dto/mapper/SeatPresentationMapper.java
Labels: ⚙️ setting

#30 [Ticket] : Ticket Service Init
  ticket-service/.gitattributes
  ticket-service/build.gradle
  ticket-service/gradle/wrapper/gradle-wrapper.jar
  ticket-service/gradle/wrapper/gradle-wrapper.properties
  ticket-service/settings.gradle
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/TicketServiceApplication.java
  ticket-service/src/main/resources/application.yml
  ticket-service/src/test/java/com/boeingmerryho/business/ticketservice/TicketServiceApplicationTests.java
Labels: ⚙️ setting

#33 [Payment] : settings, common library, 결제내역 조회, 검색, config 설정
  config-service/gradlew
  config-service/gradlew.bat
  payment-service/.gitattributes
  payment-service/build.gradle
  payment-service/gradlew
  payment-service/gradlew.bat
  payment-service/settings.gradle
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/PaymentServiceApplication.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/application/PaymentAdminService.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/application/PaymentApplicationMapper.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/application/PaymentService.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/application/dto/request/PaymentDetailRequestServiceDto.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/application/dto/request/PaymentDetailSearchRequestServiceDto.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/application/dto/response/PaymentDetailAdminResponseServiceDto.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/application/dto/response/PaymentDetailResponseServiceDto.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/domain/context/PaymentDetailSearchContext.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/domain/entity/BaseEntity.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/domain/entity/Payment.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/domain/entity/PaymentDetail.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/domain/entity/PaymentMembership.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/domain/entity/PaymentTicket.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/domain/repository/PaymentRepository.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/domain/type/DiscountType.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/domain/type/PaymentMethod.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/domain/type/PaymentStatus.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/domain/type/PaymentType.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/infrastructure/config/JpaAuditingConfig.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/infrastructure/config/QueryDslConfig.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/infrastructure/repository/PaymentJpaRepository.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/infrastructure/repository/PaymentQueryRepository.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/infrastructure/repository/PaymentRepositoryImpl.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/presentation/PaymentAdminController.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/presentation/PaymentController.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/presentation/PaymentPresentationMapper.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/presentation/PaymentSuccessCode.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/presentation/dto/response/PaymentDetailAdminResponseDto.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/presentation/dto/response/PaymentDetailResponseDto.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/utils/PageableUtils.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/utils/QueryDslUtils.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/utils/SortConstants.java
  payment-service/src/main/resources/application.yml
  payment-service/src/test/java/com/boeingmerryho/business/paymentservice/PaymentserviceApplicationTests.java
Labels: ✏️ feat

#43 [Seat] : ADMIN - 좌석 생성하기
  seat-service/build.gradle
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/application/dto/mapper/SeatApplicationMapper.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/application/dto/request/SeatCreateServiceRequestDto.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/application/dto/response/SeatCreateServiceResponseDto.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/application/service/SeatAdminService.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/application/service/SeatService.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/domain/BaseEntity.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/domain/Seat.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/domain/SeatReservation.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/infrastructure/SeatRepository.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/presentation/SeatSuccessCode.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/presentation/controller/SeatAdminController.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/presentation/controller/SeatController.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/presentation/dto/mapper/SeatPresentationMapper.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/presentation/dto/request/SeatCreateRequestDto.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/presentation/dto/response/SeatCreateResponseDto.java
Labels: ✏️ feat

#38 [Store] settings 및 create api 추가
  eureka-service/gradlew
  eureka-service/gradlew.bat
  store-service/.gitattributes
  store-service/build.gradle
  store-service/gradle/wrapper/gradle-wrapper.jar
  store-service/gradle/wrapper/gradle-wrapper.properties
  store-service/gradlew
  store-service/gradlew.bat
  store-service/settings.gradle
  store-service/src/main/java/com/boeingmerryho/business/storeservice/StoreServiceApplication.java
  store-service/src/main/java/com/boeingmerryho/business/storeservice/application/dto/mapper/StoreApplicationMapper.java
  store-service/src/main/java/com/boeingmerryho/business/storeservice/application/dto/request/StoreCreateRequestServiceDto.java
  store-service/src/main/java/com/boeingmerryho/business/storeservice/application/dto/response/StoreCreateResponseServiceDto.java
  store-service/src/main/java/com/boeingmerryho/business/storeservice/application/service/StoreAdminService.java
  store-service/src/main/java/com/boeingmerryho/business/storeservice/config/auditing/JpaAuditingConfig.java
  store-service/src/main/java/com/boeingmerryho/business/storeservice/domain/entity/Store.java
  store-service/src/main/java/com/boeingmerryho/business/storeservice/domain/reader/StadiumReader.java
  store-service/src/main/java/com/boeingmerryho/business/storeservice/domain/repository/StoreRepository.java
  store-service/src/main/java/com/boeingmerryho/business/storeservice/domain/service/StoreDomainService.java
  store-service/src/main/java/com/boeingmerryho/business/storeservice/domain/service/StoreValidator.java
  store-service/src/main/java/com/boeingmerryho/business/storeservice/exception/GlobalExceptionHandler.java
  store-service/src/main/java/com/boeingmerryho/business/storeservice/exception/StoreErrorCode.java
  store-service/src/main/java/com/boeingmerryho/business/storeservice/infrastructure/reader/StadiumReaderImpl.java
  store-service/src/main/java/com/boeingmerryho/business/storeservice/infrastructure/repository/StoreJpaRepository.java
  store-service/src/main/java/com/boeingmerryho/business/storeservice/infrastructure/repository/StoreRepositoryImpl.java
  store-service/src/main/java/com/boeingmerryho/business/storeservice/presentation/StoreSuccessCode.java
  store-service/src/main/java/com/boeingmerryho/business/storeservice/presentation/controller/StoreAdminController.java
  store-service/src/main/java/com/boeingmerryho/business/storeservice/presentation/dto/mapper/StorePresentationMapper.java
  store-service/src/main/java/com/boeingmerryho/business/storeservice/presentation/dto/request/StoreCreateRequestDto.java
  store-service/src/main/java/com/boeingmerryho/business/storeservice/presentation/dto/response/StoreCreateResponseDto.java
  store-service/src/main/resources/application.yml
  store-service/src/test/java/com/boeingmerryho/business/storeservice/StoreServiceApplicationTests.java
Labels: ✏️ feat, ⚙️ setting

#44 [Seat] : ADMIN - 좌석 생성하기
  seat-service/build.gradle
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/application/dto/mapper/SeatApplicationMapper.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/application/dto/request/SeatCreateServiceRequestDto.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/application/dto/response/SeatCreateServiceResponseDto.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/application/service/SeatAdminService.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/application/service/SeatService.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/domain/BaseEntity.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/domain/Seat.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/domain/SeatReservation.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/infrastructure/SeatRepository.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/presentation/SeatSuccessCode.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/presentation/controller/SeatAdminController.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/presentation/controller/SeatController.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/presentation/dto/mapper/SeatPresentationMapper.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/presentation/dto/request/SeatCreateRequestDto.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/presentation/dto/response/SeatCreateResponseDto.java
Labels: ✏️ feat

#51 [Seat] : ADMIN - 좌석 이용 가능/불가능 #50
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/application/dto/mapper/SeatApplicationMapper.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/application/dto/request/SeatActiveServiceRequestDto.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/application/dto/request/SeatInActiveServiceRequestDto.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/application/dto/response/SeatActiveServiceResponseDto.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/application/dto/response/SeatInActiveServiceResponseDto.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/application/service/SeatAdminService.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/domain/Seat.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/exception/GlobalExceptionHandler.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/exception/SeatErrorCode.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/infrastructure/helper/SeatServiceHelper.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/presentation/controller/SeatAdminController.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/presentation/dto/mapper/SeatPresentationMapper.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/presentation/dto/response/SeatResponseDto.java
Labels: ✏️ feat

#52 [Seat] : 좌석 이용 가능/불가능 #50
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/application/dto/mapper/SeatApplicationMapper.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/application/dto/request/SeatActiveServiceRequestDto.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/application/dto/request/SeatInActiveServiceRequestDto.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/application/dto/response/SeatActiveServiceResponseDto.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/application/dto/response/SeatInActiveServiceResponseDto.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/application/service/SeatAdminService.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/domain/Seat.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/exception/GlobalExceptionHandler.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/exception/SeatErrorCode.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/infrastructure/helper/SeatServiceHelper.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/presentation/controller/SeatAdminController.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/presentation/dto/mapper/SeatPresentationMapper.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/presentation/dto/response/SeatResponseDto.java
Labels: ✏️ feat

#57 [Seat] : ADMIN - 좌석 삭제하기 #56
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/application/dto/request/SeatDeleteServiceRequestDto.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/application/service/SeatAdminService.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/infrastructure/helper/SeatAdminServiceHelper.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/infrastructure/helper/SeatCommonHelper.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/presentation/controller/SeatAdminController.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/presentation/dto/mapper/SeatPresentationMapper.java
Labels: ✏️ feat

#58 [Seat] - 좌석 삭제하기 #56
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/application/dto/request/SeatDeleteServiceRequestDto.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/application/service/SeatAdminService.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/infrastructure/helper/SeatAdminServiceHelper.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/infrastructure/helper/SeatCommonHelper.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/presentation/controller/SeatAdminController.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/presentation/dto/mapper/SeatPresentationMapper.java
Labels: ✏️ feat

#63 [Ticket] : 관리자 티켓 기능
  ticket-service/build.gradle
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/application/admin/AdminTicketService.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/application/admin/dto/mapper/AdminTicketApplicationMapper.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/application/admin/dto/request/AdminTicketDeleteRequestServiceDto.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/application/admin/dto/request/AdminTicketIdRequestServiceDto.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/application/admin/dto/request/AdminTicketSearchRequestServiceDto.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/application/admin/dto/request/AdminTicketStatusUpdateRequestServiceDto.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/application/admin/dto/response/AdminTicketResponseServiceDto.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/config/PageableConfig.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/config/QueryDslConfig.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/domain/Ticket.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/domain/TicketSearchCriteria.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/domain/TicketStatus.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/domain/repository/TicketRepository.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/exception/ErrorCode.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/exception/GlobalExceptionHandler.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/exception/TicketException.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/infrastructure/repository/TicketJpaRepository.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/infrastructure/repository/TicketQueryRepository.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/infrastructure/repository/TicketRepositoryImpl.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/presentation/TicketSuccessCode.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/presentation/admin/AdminTicketController.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/presentation/admin/dto/mapper/AdminTicketPresentationMapper.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/presentation/admin/dto/request/AdminTicketSearchRequestDto.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/presentation/admin/dto/request/AdminTicketStatusUpdateRequestDto.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/presentation/admin/dto/response/AdminTicketResponseDto.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/utils/PageableUtils.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/utils/QueryDslUtils.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/utils/SortConstants.java
  ticket-service/src/test/java/com/boeingmerryho/business/ticketservice/application/admin/AdminTicketServiceTest.java
Labels: ✏️ feat, 📑 test

#67 [Seat] : ADMIN - 예약 가능 좌석 생성하기 #66
  seat-service/build.gradle
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/SeatServiceApplication.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/application/dto/request/CacheSeatCreateServiceRequestDto.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/application/service/SeatAdminService.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/config/RedissonConfig.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/domain/ReservationStatus.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/domain/service/CreateCacheSeatsService.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/infrastructure/SeatRepository.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/infrastructure/helper/SeatAdminServiceHelper.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/presentation/controller/SeatAdminController.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/presentation/dto/mapper/SeatPresentationMapper.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/presentation/dto/request/CacheSeatCreateRequestDto.java
Labels: ✏️ feat

#68 [Seat] : ADMIN - 예약 가능 좌석 생성하기 #66
  seat-service/build.gradle
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/SeatServiceApplication.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/application/dto/request/CacheSeatCreateServiceRequestDto.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/application/service/SeatAdminService.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/config/RedissonConfig.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/domain/ReservationStatus.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/domain/service/CreateCacheSeatsService.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/infrastructure/SeatRepository.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/infrastructure/helper/SeatAdminServiceHelper.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/presentation/controller/SeatAdminController.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/presentation/dto/mapper/SeatPresentationMapper.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/presentation/dto/request/CacheSeatCreateRequestDto.java
Labels: ✏️ feat

#84 [Seat] : ADMIN - 예약 가능 좌석 생성하기 #66
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/domain/service/CreateCacheSeatsService.java
Labels: ✏️ feat

#85 [Seat] : ADMIN - 예약 가능 좌석 생성하기 #66
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/domain/service/CreateCacheSeatsService.java
Labels: ✏️ feat

#91 [Seat] : 좌석 전체 조회 #86
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/application/dto/mapper/SeatApplicationMapper.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/application/dto/request/CacheBlockServiceRequestDto.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/application/dto/response/CacheBlockServiceResponseDto.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/application/dto/response/CacheSeatServiceResponseDto.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/application/service/SeatService.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/domain/service/GetCacheBlockSeatsService.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/exception/SeatErrorCode.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/presentation/SeatSuccessCode.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/presentation/controller/SeatController.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/presentation/dto/mapper/SeatPresentationMapper.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/presentation/dto/response/CacheBlockResponseDto.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/presentation/dto/response/CacheSeatResponseDto.java
Labels: ✏️ feat

#89 [User] : membership 정보 feign 요청 및 redis에서 삭제 기능 추가
  user-service/build.gradle
  user-service/src/main/java/com/boeingmerryho/business/userservice/UserServiceApplication.java
  user-service/src/main/java/com/boeingmerryho/business/userservice/application/UserHelper.java
  user-service/src/main/java/com/boeingmerryho/business/userservice/application/dto/request/feign/LoginSuccessRequest.java
  user-service/src/main/java/com/boeingmerryho/business/userservice/application/feign/MembershipClient.java
  user-service/src/main/java/com/boeingmerryho/business/userservice/application/service/UserAdminService.java
  user-service/src/main/java/com/boeingmerryho/business/userservice/application/service/UserService.java
  user-service/src/main/java/com/boeingmerryho/business/userservice/exception/ErrorCode.java
  user-service/src/main/java/com/boeingmerryho/business/userservice/infrastructure/UserHelperImpl.java
  user-service/src/test/java/com/boeingmerryho/business/userservice/infrastructure/UserHelperImplLoginTest.java
Labels: ✏️ feat, 🔧 fix, 📑 test

#92 [Seat] : 좌석 전체 조회 #86
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/application/dto/mapper/SeatApplicationMapper.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/application/dto/request/CacheBlockServiceRequestDto.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/application/dto/response/CacheBlockServiceResponseDto.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/application/dto/response/CacheSeatServiceResponseDto.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/application/service/SeatService.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/domain/service/GetCacheBlockSeatsService.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/exception/SeatErrorCode.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/presentation/SeatSuccessCode.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/presentation/controller/SeatController.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/presentation/dto/mapper/SeatPresentationMapper.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/presentation/dto/response/CacheBlockResponseDto.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/presentation/dto/response/CacheSeatResponseDto.java
Labels: ✏️ feat

#109 refactor: payment - class->record#45
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/application/dto/kakao/Amount.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/application/dto/kakao/ApprovedCancelAmount.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/application/dto/kakao/CancelAvailableAmount.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/application/dto/kakao/CanceledAmount.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/application/dto/kakao/CardInfo.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/application/dto/kakao/KakaoPayApproveRequest.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/application/dto/kakao/KakaoPayApproveResponse.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/application/dto/kakao/KakaoPayCancelRequest.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/application/dto/kakao/KakaoPayCancelResponse.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/application/dto/kakao/KakaoPayReadyRequest.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/application/dto/kakao/KakaoPayReadyResponse.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/application/dto/kakao/KakaoPaymentSession.java
Labels: 🛠️ refactor

#114 [Ticket] - 사용자 티켓 검색 및 조회
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/application/user/TicketService.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/application/user/dto/mapper/TicketApplicationMapper.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/application/user/dto/request/TicketByIdRequestServiceDto.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/application/user/dto/request/TicketSearchRequestServiceDto.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/application/user/dto/response/TicketResponseServiceDto.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/domain/repository/TicketRepository.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/infrastructure/repository/TicketQueryRepository.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/infrastructure/repository/TicketRepositoryImpl.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/presentation/user/TicketController.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/presentation/user/dto/mapper/TicketPresentationMapper.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/presentation/user/dto/request/TicketSearchRequestDto.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/presentation/user/dto/response/TicketResponseDto.java
Labels: ✏️ feat

#115 [Ticket] : 사용자 티켓 검색 및 조회
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/application/user/TicketService.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/application/user/dto/mapper/TicketApplicationMapper.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/application/user/dto/request/TicketByIdRequestServiceDto.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/application/user/dto/request/TicketSearchRequestServiceDto.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/application/user/dto/response/TicketResponseServiceDto.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/domain/repository/TicketRepository.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/infrastructure/repository/TicketQueryRepository.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/infrastructure/repository/TicketRepositoryImpl.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/presentation/user/TicketController.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/presentation/user/dto/mapper/TicketPresentationMapper.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/presentation/user/dto/request/TicketSearchRequestDto.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/presentation/user/dto/response/TicketResponseDto.java
Labels: ✏️ feat

#121 [Ticket] : 좌석 서비스로부터 티켓 생성
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/application/user/TicketService.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/config/JpaAuditingConfig.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/domain/repository/TicketRepository.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/domain/service/CreateTicketService.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/infrastructure/adapter/kafka/SeatEventConsumer.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/infrastructure/adapter/kafka/dto/response/MatchInfo.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/infrastructure/adapter/kafka/dto/response/SeatInfo.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/infrastructure/adapter/kafka/dto/response/SeatListenerDto.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/infrastructure/auditing/CustomAuditorAware.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/infrastructure/repository/TicketRepositoryImpl.java
Labels: ✏️ feat

#123 [Payment]
  eureka-service/src/main/resources/db/migration/V32__alter_payment.sql
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/application/PaySessionService.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/application/PaymentAdminService.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/application/PaymentFeignService.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/application/dto/PaymentApplicationMapper.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/application/dto/request/PaymentApproveAdminRequestServiceDto.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/application/dto/request/PaymentCreationRequestServiceDto.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/application/dto/response/PaymentCreationResponseServiceDto.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/domain/entity/Payment.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/domain/entity/PaymentMembership.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/domain/repository/PaymentRepository.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/domain/type/DiscountType.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/domain/type/PaymentType.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/infrastructure/KakaoPayStrategy.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/infrastructure/PaySessionHelper.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/infrastructure/config/RedisConfig.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/infrastructure/exception/ErrorCode.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/infrastructure/repository/PaymentRepositoryImpl.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/infrastructure/service/PaySessionServiceImpl.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/infrastructure/service/PaymentAdminServiceImpl.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/infrastructure/service/PaymentFeignServiceImpl.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/infrastructure/service/PaymentServiceImpl.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/presentation/PaymentAdminController.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/presentation/PaymentController.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/presentation/PaymentFeignController.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/presentation/dto/PaymentPresentationMapper.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/presentation/dto/request/PaymentCreationRequestDto.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/presentation/dto/request/Ticket.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/presentation/dto/response/PaymentCreationResponseDto.java
Labels: ✏️ feat

#122 [Ticket] : 좌석 서비스로부터 티켓 생성
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/application/user/TicketService.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/config/JpaAuditingConfig.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/domain/repository/TicketRepository.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/domain/service/CreateTicketService.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/infrastructure/adapter/kafka/SeatEventConsumer.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/infrastructure/adapter/kafka/dto/response/MatchInfo.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/infrastructure/adapter/kafka/dto/response/SeatInfo.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/infrastructure/adapter/kafka/dto/response/SeatListenerDto.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/infrastructure/auditing/CustomAuditorAware.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/infrastructure/repository/TicketRepositoryImpl.java
Labels: ✏️ feat

#124 [Payment] : 결제 생성 feign service, expired 시간 검증 로직
  eureka-service/src/main/resources/db/migration/V32__alter_payment.sql
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/application/PaySessionService.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/application/PaymentAdminService.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/application/PaymentFeignService.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/application/dto/PaymentApplicationMapper.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/application/dto/request/PaymentApproveAdminRequestServiceDto.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/application/dto/request/PaymentCreationRequestServiceDto.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/application/dto/response/PaymentCreationResponseServiceDto.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/domain/entity/Payment.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/domain/entity/PaymentMembership.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/domain/repository/PaymentRepository.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/domain/type/DiscountType.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/domain/type/PaymentType.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/infrastructure/KakaoPayStrategy.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/infrastructure/PaySessionHelper.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/infrastructure/config/RedisConfig.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/infrastructure/exception/ErrorCode.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/infrastructure/repository/PaymentRepositoryImpl.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/infrastructure/service/PaySessionServiceImpl.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/infrastructure/service/PaymentAdminServiceImpl.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/infrastructure/service/PaymentFeignServiceImpl.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/infrastructure/service/PaymentServiceImpl.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/presentation/PaymentAdminController.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/presentation/PaymentController.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/presentation/PaymentFeignController.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/presentation/dto/PaymentPresentationMapper.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/presentation/dto/request/PaymentCreationRequestDto.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/presentation/dto/request/Ticket.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/presentation/dto/response/PaymentCreationResponseDto.java
Labels: ✏️ feat

#127 [Membership] membership field 수정 및 reserve api 추가
  eureka-service/src/main/resources/db/migration/V29__create_partitioned_membership_user.sql
  eureka-service/src/main/resources/db/migration/V30__alter_membership.sql
  eureka-service/src/main/resources/db/migration/V31__alter_membership.sql
  membership-service/build.gradle
  membership-service/src/main/java/com/boeingmerryho/business/membershipservice/MembershipServiceApplication.java
  membership-service/src/main/java/com/boeingmerryho/business/membershipservice/application/dto/mapper/MembershipApplicationMapper.java
  membership-service/src/main/java/com/boeingmerryho/business/membershipservice/application/dto/query/MembershipSearchCondition.java
  membership-service/src/main/java/com/boeingmerryho/business/membershipservice/application/dto/request/MembershipCreateRequestServiceDto.java
  membership-service/src/main/java/com/boeingmerryho/business/membershipservice/application/dto/request/MembershipUpdateRequestServiceDto.java
  membership-service/src/main/java/com/boeingmerryho/business/membershipservice/application/dto/request/MembershipUserCreateRequestServiceDto.java
  membership-service/src/main/java/com/boeingmerryho/business/membershipservice/application/dto/request/PaymentRequestDto.java
  membership-service/src/main/java/com/boeingmerryho/business/membershipservice/application/dto/response/MembershipCreateResponseServiceDto.java
  membership-service/src/main/java/com/boeingmerryho/business/membershipservice/application/dto/response/MembershipDetailAdminResponseServiceDto.java
  membership-service/src/main/java/com/boeingmerryho/business/membershipservice/application/dto/response/MembershipDetailResponseServiceDto.java
  membership-service/src/main/java/com/boeingmerryho/business/membershipservice/application/dto/response/MembershipSearchAdminResponseServiceDto.java
  membership-service/src/main/java/com/boeingmerryho/business/membershipservice/application/dto/response/MembershipUpdateResponseServiceDto.java
  membership-service/src/main/java/com/boeingmerryho/business/membershipservice/application/dto/response/MembershipUserCreateResponseServiceDto.java
  membership-service/src/main/java/com/boeingmerryho/business/membershipservice/application/service/admin/MembershipAdminService.java
  membership-service/src/main/java/com/boeingmerryho/business/membershipservice/application/service/user/MembershipReserveService.java
  membership-service/src/main/java/com/boeingmerryho/business/membershipservice/domain/entity/Membership.java
  membership-service/src/main/java/com/boeingmerryho/business/membershipservice/domain/type/MembershipType.java
  membership-service/src/main/java/com/boeingmerryho/business/membershipservice/exception/GlobalExceptionHandler.java
  membership-service/src/main/java/com/boeingmerryho/business/membershipservice/exception/MembershipErrorCode.java
  membership-service/src/main/java/com/boeingmerryho/business/membershipservice/infrastructure/PaymentApiClient.java
  membership-service/src/main/java/com/boeingmerryho/business/membershipservice/infrastructure/client/PaymentFeignClient.java
  membership-service/src/main/java/com/boeingmerryho/business/membershipservice/infrastructure/config/RedisConfig.java
  membership-service/src/main/java/com/boeingmerryho/business/membershipservice/infrastructure/helper/MembershipAdminHelper.java
  membership-service/src/main/java/com/boeingmerryho/business/membershipservice/infrastructure/helper/MembershipHelper.java
  membership-service/src/main/java/com/boeingmerryho/business/membershipservice/infrastructure/helper/MembershipRedisHelper.java
  membership-service/src/main/java/com/boeingmerryho/business/membershipservice/infrastructure/helper/MembershipValidator.java
  membership-service/src/main/java/com/boeingmerryho/business/membershipservice/infrastructure/repository/MembershipQueryRepositoryImpl.java
  membership-service/src/main/java/com/boeingmerryho/business/membershipservice/presentation/controller/admin/MembershipAdminController.java
  membership-service/src/main/java/com/boeingmerryho/business/membershipservice/presentation/controller/user/MembershipController.java
  membership-service/src/main/java/com/boeingmerryho/business/membershipservice/presentation/dto/MembershipSuccessCode.java
  membership-service/src/main/java/com/boeingmerryho/business/membershipservice/presentation/dto/mapper/MembershipPresentationMapper.java
  membership-service/src/main/java/com/boeingmerryho/business/membershipservice/presentation/dto/request/MembershipCreateRequestDto.java
  membership-service/src/main/java/com/boeingmerryho/business/membershipservice/presentation/dto/request/MembershipSearchAdminRequestServiceDto.java
  membership-service/src/main/java/com/boeingmerryho/business/membershipservice/presentation/dto/request/MembershipUpdateRequestDto.java
  membership-service/src/main/java/com/boeingmerryho/business/membershipservice/presentation/dto/request/MembershipUserCreateRequestDto.java
  membership-service/src/main/java/com/boeingmerryho/business/membershipservice/presentation/dto/response/MembershipCreateResponseDto.java
  membership-service/src/main/java/com/boeingmerryho/business/membershipservice/presentation/dto/response/MembershipDetailAdminResponseDto.java
  membership-service/src/main/java/com/boeingmerryho/business/membershipservice/presentation/dto/response/MembershipDetailResponseDto.java
  membership-service/src/main/java/com/boeingmerryho/business/membershipservice/presentation/dto/response/MembershipSearchAdminResponseDto.java
  membership-service/src/main/java/com/boeingmerryho/business/membershipservice/presentation/dto/response/MembershipUpdateResponseDto.java
  membership-service/src/main/java/com/boeingmerryho/business/membershipservice/presentation/dto/response/MembershipUserCreateResponseDto.java
Labels: ✏️ feat, 🛠️ refactor

#128 [Seat] : 좌석 선점 #98
  seat-service/build.gradle
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/application/dto/mapper/SeatApplicationMapper.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/application/dto/request/CacheSeatProcessServiceRequestDto.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/application/dto/request/CacheSeatsProcessServiceRequestDto.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/application/dto/request/ToTicketDto.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/application/dto/request/ToTicketMatchDto.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/application/dto/request/ToTicketSeatDto.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/application/service/SeatService.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/domain/service/CreateCacheSeatsService.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/domain/service/ProcessBlockSeatsService.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/exception/MatchErrorCode.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/exception/SeatErrorCode.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/exception/SeatSuccessCode.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/infrastructure/helper/MatchHelper.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/infrastructure/reader/MatchReader.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/infrastructure/reader/MatchReaderImpl.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/presentation/controller/SeatAdminController.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/presentation/controller/SeatController.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/presentation/dto/mapper/SeatPresentationMapper.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/presentation/dto/request/CacheSeatProcessRequestDto.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/presentation/dto/request/CacheSeatsProcessRequestDto.java
Labels: ✏️ feat

#129 [Seat] : 좌석 선점 #98
  seat-service/build.gradle
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/application/dto/mapper/SeatApplicationMapper.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/application/dto/request/CacheSeatProcessServiceRequestDto.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/application/dto/request/CacheSeatsProcessServiceRequestDto.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/application/dto/request/ToTicketDto.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/application/dto/request/ToTicketMatchDto.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/application/dto/request/ToTicketSeatDto.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/application/service/SeatService.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/domain/service/CreateCacheSeatsService.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/domain/service/ProcessBlockSeatsService.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/exception/MatchErrorCode.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/exception/SeatErrorCode.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/exception/SeatSuccessCode.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/infrastructure/helper/MatchHelper.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/infrastructure/reader/MatchReader.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/infrastructure/reader/MatchReaderImpl.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/presentation/controller/SeatAdminController.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/presentation/controller/SeatController.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/presentation/dto/mapper/SeatPresentationMapper.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/presentation/dto/request/CacheSeatProcessRequestDto.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/presentation/dto/request/CacheSeatsProcessRequestDto.java
Labels: ✏️ feat

#136 [User] : 로그아웃, 회원 탈퇴 시 레디스에서 회원 관련 정보 모두 삭제
  user-service/src/main/java/com/boeingmerryho/business/userservice/application/service/UserAdminService.java
  user-service/src/main/java/com/boeingmerryho/business/userservice/application/service/UserService.java
  user-service/src/main/java/com/boeingmerryho/business/userservice/infrastructure/UserHelperImpl.java
Labels: ✏️ feat, 🛠️ refactor

#137 [Seat] : 티켓 카프카 응답 처리 #130
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/application/service/ListenerService.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/domain/service/SeatFailedService.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/domain/service/SeatSucceedService.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/exception/SeatErrorCode.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/infrastructure/helper/SeatListenerHelper.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/infrastructure/kafka/response/SeatFailedListener.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/infrastructure/kafka/response/SeatSucceedListener.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/presentation/dto/response/SeatListenerResponseDto.java
Labels: ✏️ feat

#139 [Seat] : 티켓 카프카 응답 처리 #130
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/application/service/ListenerService.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/domain/service/SeatFailedService.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/domain/service/SeatSucceedService.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/exception/SeatErrorCode.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/infrastructure/helper/SeatListenerHelper.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/infrastructure/kafka/response/SeatFailedListener.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/infrastructure/kafka/response/SeatSucceedListener.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/presentation/dto/response/SeatListenerResponseDto.java
Labels: ✏️ feat

#140 [Membership] feignClient payment, user
  membership-service/src/main/java/com/boeingmerryho/business/membershipservice/application/dto/mapper/MembershipApplicationMapper.java
  membership-service/src/main/java/com/boeingmerryho/business/membershipservice/application/dto/request/LoginSuccessRequest.java
  membership-service/src/main/java/com/boeingmerryho/business/membershipservice/application/dto/request/PaymentRequestDto.java
  membership-service/src/main/java/com/boeingmerryho/business/membershipservice/application/dto/request/UserDiscountRequest.java
  membership-service/src/main/java/com/boeingmerryho/business/membershipservice/application/service/feign/MembershipFeignService.java
  membership-service/src/main/java/com/boeingmerryho/business/membershipservice/domain/entity/Membership.java
  membership-service/src/main/java/com/boeingmerryho/business/membershipservice/domain/repository/MembershipRepository.java
  membership-service/src/main/java/com/boeingmerryho/business/membershipservice/domain/service/feign/MembershipFeignServiceImpl.java
  membership-service/src/main/java/com/boeingmerryho/business/membershipservice/exception/MembershipErrorCode.java
  membership-service/src/main/java/com/boeingmerryho/business/membershipservice/infrastructure/PaymentApiClient.java
  membership-service/src/main/java/com/boeingmerryho/business/membershipservice/infrastructure/config/RedisConfig.java
  membership-service/src/main/java/com/boeingmerryho/business/membershipservice/infrastructure/helper/MembershipHelper.java
  membership-service/src/main/java/com/boeingmerryho/business/membershipservice/infrastructure/helper/MembershipRedisHelper.java
  membership-service/src/main/java/com/boeingmerryho/business/membershipservice/infrastructure/helper/MembershipValidator.java
  membership-service/src/main/java/com/boeingmerryho/business/membershipservice/infrastructure/repository/MembershipJpaRepository.java
  membership-service/src/main/java/com/boeingmerryho/business/membershipservice/infrastructure/runner/MembershipAvailableQuantityPreloader.java
  membership-service/src/main/java/com/boeingmerryho/business/membershipservice/presentation/controller/admin/MembershipAdminController.java
  membership-service/src/main/java/com/boeingmerryho/business/membershipservice/presentation/controller/feign/MembershipFeignController.java
  membership-service/src/main/java/com/boeingmerryho/business/membershipservice/presentation/controller/user/MembershipController.java
Labels: ✏️ feat, 🛠️ refactor

#147 [Seat] : 코드 정리 #146
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/application/service/SeatService.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/config/JpaAuditingConfig.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/domain/service/CreateCacheSeatsService.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/domain/service/GetCacheBlockSeatsService.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/domain/service/ProcessBlockSeatsService.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/domain/service/SeatFailedService.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/domain/service/SeatSucceedService.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/infrastructure/adaptor/kafka/listener/SeatFailedListener.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/infrastructure/adaptor/kafka/listener/SeatSucceedListener.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/infrastructure/helper/SeatCommonHelper.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/infrastructure/helper/SeatListenerHelper.java
Labels: 🛠️ refactor

#148 [Seat] : 코드 정리 #146
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/application/service/SeatService.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/config/JpaAuditingConfig.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/domain/service/CreateCacheSeatsService.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/domain/service/GetCacheBlockSeatsService.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/domain/service/ProcessBlockSeatsService.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/domain/service/SeatFailedService.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/domain/service/SeatSucceedService.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/infrastructure/adaptor/kafka/listener/SeatFailedListener.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/infrastructure/adaptor/kafka/listener/SeatSucceedListener.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/infrastructure/helper/SeatCommonHelper.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/infrastructure/helper/SeatListenerHelper.java
Labels: 🛠️ refactor

#151 [User] : 코드 정리
  user-service/src/main/java/com/boeingmerryho/business/userservice/application/UserHelper.java
  user-service/src/main/java/com/boeingmerryho/business/userservice/application/UserJwtHelper.java
  user-service/src/main/java/com/boeingmerryho/business/userservice/application/UserVerificationHelper.java
  user-service/src/main/java/com/boeingmerryho/business/userservice/application/service/UserAdminService.java
  user-service/src/main/java/com/boeingmerryho/business/userservice/application/service/UserService.java
  user-service/src/main/java/com/boeingmerryho/business/userservice/application/utils/RedisUtil.java
  user-service/src/main/java/com/boeingmerryho/business/userservice/infrastructure/RedisUtilImpl.java
  user-service/src/main/java/com/boeingmerryho/business/userservice/infrastructure/UserHelperImpl.java
  user-service/src/main/java/com/boeingmerryho/business/userservice/infrastructure/helper/UserHelperImpl.java
  user-service/src/main/java/com/boeingmerryho/business/userservice/infrastructure/helper/UserJwtHelperImpl.java
  user-service/src/main/java/com/boeingmerryho/business/userservice/infrastructure/helper/UserVerificationHelperImpl.java
  user-service/src/test/java/com/boeingmerryho/business/userservice/infrastructure/UserHelperImplLoginTest.java
Labels: 🛠️ refactor

#153 Feat/membership/membership user read search
  membership-service/src/main/java/com/boeingmerryho/business/membershipservice/application/dto/query/MembershipUserSearchCondition.java
  membership-service/src/main/java/com/boeingmerryho/business/membershipservice/application/dto/request/MembershipSearchAdminRequestServiceDto.java
  membership-service/src/main/java/com/boeingmerryho/business/membershipservice/application/dto/request/MembershipUserSearchAdminRequestServiceDto.java
  membership-service/src/main/java/com/boeingmerryho/business/membershipservice/application/dto/response/MembershipUserDetailAdminResponseServiceDto.java
  membership-service/src/main/java/com/boeingmerryho/business/membershipservice/application/dto/response/MembershipUserDetailResponseServiceDto.java
  membership-service/src/main/java/com/boeingmerryho/business/membershipservice/application/dto/response/MembershipUserSearchAdminResponseServiceDto.java
  membership-service/src/main/java/com/boeingmerryho/business/membershipservice/application/service/admin/MembershipAdminService.java
  membership-service/src/main/java/com/boeingmerryho/business/membershipservice/application/service/admin/MembershipUserAdminService.java
  membership-service/src/main/java/com/boeingmerryho/business/membershipservice/application/service/user/MembershipUserService.java
  membership-service/src/main/java/com/boeingmerryho/business/membershipservice/domain/repository/MembershipRepository.java
  membership-service/src/main/java/com/boeingmerryho/business/membershipservice/domain/repository/MembershipUserQueryRepository.java
  membership-service/src/main/java/com/boeingmerryho/business/membershipservice/infrastructure/helper/MembershipAdminHelper.java
  membership-service/src/main/java/com/boeingmerryho/business/membershipservice/infrastructure/helper/MembershipHelper.java
  membership-service/src/main/java/com/boeingmerryho/business/membershipservice/infrastructure/repository/MembershipJpaRepository.java
  membership-service/src/main/java/com/boeingmerryho/business/membershipservice/infrastructure/repository/MembershipUserQueryRepositoryImpl.java
  membership-service/src/main/java/com/boeingmerryho/business/membershipservice/presentation/controller/admin/MembershipAdminController.java
  membership-service/src/main/java/com/boeingmerryho/business/membershipservice/presentation/controller/admin/MembershipUserAdminController.java
  membership-service/src/main/java/com/boeingmerryho/business/membershipservice/presentation/controller/user/MembershipUserController.java
  membership-service/src/main/java/com/boeingmerryho/business/membershipservice/presentation/dto/MembershipSuccessCode.java
  membership-service/src/main/java/com/boeingmerryho/business/membershipservice/presentation/dto/mapper/MembershipPresentationMapper.java
  membership-service/src/main/java/com/boeingmerryho/business/membershipservice/presentation/dto/response/MembershipUserDetailAdminResponseDto.java
  membership-service/src/main/java/com/boeingmerryho/business/membershipservice/presentation/dto/response/MembershipUserDetailResponseDto.java
  membership-service/src/main/java/com/boeingmerryho/business/membershipservice/presentation/dto/response/MembershipUserSearchAdminResponseDto.java
Labels: ✏️ feat

#157 [Payment] : kafka
  eureka-service/src/main/resources/db/migration/V34__alter_payment_membership.sql
  payment-service/build.gradle
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/application/PaySessionService.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/application/PaymentStrategy.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/application/dto/kafka/MembershipPaymentEvent.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/application/dto/kafka/TicketPaymentEvent.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/application/dto/membership/UserDiscountRequest.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/application/dto/request/PaymentCreationRequestServiceDto.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/domain/entity/Payment.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/domain/entity/PaymentDetail.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/domain/entity/PaymentMembership.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/domain/type/DiscountType.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/infrastructure/BankTransferStrategy.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/infrastructure/KafkaProducerHelper.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/infrastructure/KakaoPayStrategy.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/infrastructure/MembershipApiClient.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/infrastructure/PaySessionHelper.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/infrastructure/config/KafkaConfig.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/infrastructure/config/RedisConfig.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/infrastructure/exception/ErrorCode.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/infrastructure/feignclient/MembershipFeignClient.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/infrastructure/kafka/producer/MembershipKafkaProducer.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/infrastructure/kafka/producer/TicketKafkaProducer.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/infrastructure/service/BankTransferStrategy.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/infrastructure/service/KakaoPayStrategy.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/infrastructure/service/PaySessionServiceImpl.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/infrastructure/service/PaymentAdminServiceImpl.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/infrastructure/service/PaymentFeignServiceImpl.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/infrastructure/service/PaymentServiceImpl.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/presentation/dto/request/PaymentCreationRequestDto.java
Labels: ✏️ feat

#156 [MembershipUser] MembershipUser 시즌 종료 후 deactivate 배치 처리
  membership-service/src/main/java/com/boeingmerryho/business/membershipservice/application/service/admin/MembershipUserAdminService.java
  membership-service/src/main/java/com/boeingmerryho/business/membershipservice/application/service/scheduler/MembershipUserScheduler.java
  membership-service/src/main/java/com/boeingmerryho/business/membershipservice/domain/repository/MembershipRepository.java
  membership-service/src/main/java/com/boeingmerryho/business/membershipservice/infrastructure/helper/MembershipAdminHelper.java
  membership-service/src/main/java/com/boeingmerryho/business/membershipservice/infrastructure/repository/MembershipJpaRepository.java
  membership-service/src/main/java/com/boeingmerryho/business/membershipservice/presentation/controller/admin/MembershipUserAdminController.java
  membership-service/src/main/java/com/boeingmerryho/business/membershipservice/presentation/dto/MembershipSuccessCode.java
Labels: ✏️ feat

#158 [Payment] : 결제 성공/실패 시 Kafka Producing
  eureka-service/src/main/resources/db/migration/V34__alter_payment_membership.sql
  payment-service/build.gradle
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/application/PaySessionService.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/application/PaymentStrategy.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/application/dto/kafka/MembershipPaymentEvent.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/application/dto/kafka/TicketPaymentEvent.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/application/dto/membership/UserDiscountRequest.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/application/dto/request/PaymentCreationRequestServiceDto.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/domain/entity/Payment.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/domain/entity/PaymentDetail.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/domain/entity/PaymentMembership.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/domain/type/DiscountType.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/infrastructure/BankTransferStrategy.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/infrastructure/KafkaProducerHelper.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/infrastructure/KakaoPayStrategy.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/infrastructure/MembershipApiClient.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/infrastructure/PaySessionHelper.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/infrastructure/config/KafkaConfig.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/infrastructure/config/RedisConfig.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/infrastructure/exception/ErrorCode.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/infrastructure/feignclient/MembershipFeignClient.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/infrastructure/kafka/producer/MembershipKafkaProducer.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/infrastructure/kafka/producer/TicketKafkaProducer.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/infrastructure/service/BankTransferStrategy.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/infrastructure/service/KakaoPayStrategy.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/infrastructure/service/PaySessionServiceImpl.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/infrastructure/service/PaymentAdminServiceImpl.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/infrastructure/service/PaymentFeignServiceImpl.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/infrastructure/service/PaymentServiceImpl.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/presentation/dto/request/PaymentCreationRequestDto.java
Labels: ✏️ feat

#161 [Payment] : 멤버십 도메인과 연결 시 이슈 해결
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/infrastructure/config/RedisConfig.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/infrastructure/kafka/producer/MembershipKafkaProducer.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/infrastructure/kafka/producer/TicketKafkaProducer.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/presentation/PaymentFeignController.java
Labels: 🔧 fix

#174 [Membership] userId 권한 확인
  membership-service/build.gradle
  membership-service/src/main/java/com/boeingmerryho/business/membershipservice/domain/service/feign/MembershipFeignServiceImpl.java
  membership-service/src/main/java/com/boeingmerryho/business/membershipservice/infrastructure/client/PaymentFeignClient.java
  membership-service/src/main/java/com/boeingmerryho/business/membershipservice/infrastructure/config/auth/RedisUserInfoProvider.java
  membership-service/src/main/java/com/boeingmerryho/business/membershipservice/infrastructure/config/auth/WebMvcConfig.java
  membership-service/src/main/java/com/boeingmerryho/business/membershipservice/presentation/controller/admin/MembershipAdminController.java
  membership-service/src/main/java/com/boeingmerryho/business/membershipservice/presentation/controller/admin/MembershipUserAdminController.java
  membership-service/src/main/java/com/boeingmerryho/business/membershipservice/presentation/controller/feign/MembershipFeignController.java
  membership-service/src/main/java/com/boeingmerryho/business/membershipservice/presentation/controller/user/MembershipController.java
  membership-service/src/main/java/com/boeingmerryho/business/membershipservice/presentation/controller/user/MembershipUserController.java
Labels: ✏️ feat, 🛠️ refactor

#178 [Payment] : interceptor, config
  payment-service/build.gradle
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/application/PaymentFeignService.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/application/dto/PaymentApplicationMapper.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/application/dto/request/PaymentDetailRequestServiceDto.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/application/dto/request/PaymentMembershipCancelRequestServiceDto.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/application/dto/request/PaymentTicketCancelRequestServiceDto.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/application/dto/response/PaymentReadyResponseServiceDto.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/infrastructure/config/RedisConfig.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/infrastructure/config/auth/RedisUserInfoProvider.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/infrastructure/config/auth/WebMvcConfig.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/infrastructure/feignclient/MembershipFeignClient.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/infrastructure/service/BankTransferStrategy.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/infrastructure/service/KakaoPayStrategy.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/infrastructure/service/PaymentFeignServiceImpl.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/presentation/PaymentAdminController.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/presentation/PaymentController.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/presentation/PaymentFeignController.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/presentation/dto/PaymentPresentationMapper.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/presentation/dto/response/PaymentReadyResponseDto.java
  payment-service/src/main/resources/application.yml
Labels: ✏️ feat

#180 [Ticket] : 티켓 정보를 통해 결제 생성 요청 및 티켓 결제 정보 조회
  ticket-service/build.gradle
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/TicketServiceApplication.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/application/admin/dto/response/AdminTicketResponseServiceDto.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/application/feign/PaymentClient.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/application/feign/dto/request/PaymentCreationRequestDto.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/application/feign/dto/response/PaymentCreationResponseDto.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/application/user/TicketPaymentService.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/application/user/TicketService.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/application/user/dto/request/TicketPaymentRequestServiceDto.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/application/user/dto/response/TicketInfo.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/application/user/dto/response/TicketPaymentResponseServiceDto.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/application/user/dto/response/TicketResponseServiceDto.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/config/auth/RedisUserInfoProvider.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/config/auth/WebMvcConfig.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/config/redis/CommonRedisConfig.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/config/redis/TicketRedisConfig.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/domain/Ticket.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/domain/service/CreateTicketService.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/exception/ErrorCode.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/infrastructure/adapter/kafka/dto/response/SeatInfo.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/infrastructure/service/TicketPaymentServiceImpl.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/presentation/TicketSuccessCode.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/presentation/admin/dto/response/AdminTicketResponseDto.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/presentation/user/TicketController.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/presentation/user/dto/mapper/TicketPresentationMapper.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/presentation/user/dto/response/TicketInfo.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/presentation/user/dto/response/TicketPaymentResponseDto.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/presentation/user/dto/response/TicketResponseDto.java
Labels: ✏️ feat

#181 [Ticket] : 티켓 정보를 통해 결제 생성 요청 및 티켓 결제 정보 조회
  ticket-service/build.gradle
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/TicketServiceApplication.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/application/admin/dto/response/AdminTicketResponseServiceDto.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/application/feign/PaymentClient.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/application/feign/dto/request/PaymentCreationRequestDto.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/application/feign/dto/response/PaymentCreationResponseDto.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/application/user/TicketPaymentService.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/application/user/TicketService.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/application/user/dto/request/TicketPaymentRequestServiceDto.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/application/user/dto/response/TicketInfo.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/application/user/dto/response/TicketPaymentResponseServiceDto.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/application/user/dto/response/TicketResponseServiceDto.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/config/auth/RedisUserInfoProvider.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/config/auth/WebMvcConfig.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/config/redis/CommonRedisConfig.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/config/redis/TicketRedisConfig.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/domain/Ticket.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/domain/service/CreateTicketService.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/exception/ErrorCode.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/infrastructure/adapter/kafka/dto/response/SeatInfo.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/infrastructure/service/TicketPaymentServiceImpl.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/presentation/TicketSuccessCode.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/presentation/admin/dto/response/AdminTicketResponseDto.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/presentation/user/TicketController.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/presentation/user/dto/mapper/TicketPresentationMapper.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/presentation/user/dto/response/TicketInfo.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/presentation/user/dto/response/TicketPaymentResponseDto.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/presentation/user/dto/response/TicketResponseDto.java
Labels: ✏️ feat

#183 [User] : 공용 인터셉터 코드 추가 및 로그아웃 코드 수정
  user-service/build.gradle
  user-service/src/main/java/com/boeingmerryho/business/userservice/application/feign/MembershipClient.java
  user-service/src/main/java/com/boeingmerryho/business/userservice/application/service/UserAdminService.java
  user-service/src/main/java/com/boeingmerryho/business/userservice/application/service/UserService.java
  user-service/src/main/java/com/boeingmerryho/business/userservice/application/utils/RedisUtil.java
  user-service/src/main/java/com/boeingmerryho/business/userservice/config/RedisConfig.java
  user-service/src/main/java/com/boeingmerryho/business/userservice/config/auth/RedisUserInfoProvider.java
  user-service/src/main/java/com/boeingmerryho/business/userservice/config/auth/WebMvcConfig.java
  user-service/src/main/java/com/boeingmerryho/business/userservice/exception/ErrorCode.java
  user-service/src/main/java/com/boeingmerryho/business/userservice/infrastructure/RedisUtilImpl.java
  user-service/src/main/java/com/boeingmerryho/business/userservice/infrastructure/helper/UserHelperImpl.java
  user-service/src/main/java/com/boeingmerryho/business/userservice/presentation/controller/UserAdminController.java
  user-service/src/main/java/com/boeingmerryho/business/userservice/presentation/controller/UserController.java
  user-service/src/main/java/com/boeingmerryho/business/userservice/presentation/dto/mapper/UserPresentationMapper.java
  user-service/src/main/java/com/boeingmerryho/business/userservice/presentation/dto/request/admin/UserAdminLogoutRequestDto.java
  user-service/src/main/java/com/boeingmerryho/business/userservice/presentation/interceptor/AdminCheckInterceptor.java
  user-service/src/main/java/com/boeingmerryho/business/userservice/presentation/interceptor/UserCheckInterceptor.java
Labels: 🛠️ refactor, ⚙️ setting

#186 [Seat] : 통합 라이브러리 연동 #145
  seat-service/build.gradle
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/application/service/SeatAdminService.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/application/service/SeatService.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/config/auditing/JpaAuditingConfig.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/config/redis/RedisConfig.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/config/redis/RedisUserInfoProvider.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/config/redis/RedissonConfig.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/config/web/WebMvcConfig.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/domain/service/ProcessBlockSeatsService.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/presentation/controller/SeatController.java
Labels: ✏️ feat

#185 [Store] 공통 인터셉터 설정
  store-service/build.gradle
  store-service/src/main/java/com/boeingmerryho/business/storeservice/infrastructure/config/RedisConfig.java
  store-service/src/main/java/com/boeingmerryho/business/storeservice/infrastructure/config/auth/RedisUserInfoProvider.java
  store-service/src/main/java/com/boeingmerryho/business/storeservice/infrastructure/config/auth/WebMvcConfig.java
  store-service/src/main/java/com/boeingmerryho/business/storeservice/infrastructure/helper/StoreQueueAdminHelper.java
  store-service/src/main/java/com/boeingmerryho/business/storeservice/infrastructure/kafka/consumer/StoreQueueKafkaConsumer.java
  store-service/src/main/java/com/boeingmerryho/business/storeservice/presentation/controller/StoreAdminController.java
  store-service/src/main/java/com/boeingmerryho/business/storeservice/presentation/controller/StoreController.java
  store-service/src/main/java/com/boeingmerryho/business/storeservice/presentation/controller/StoreQueueScheduleTestController.java
Labels: ✏️ feat

#187 [Seat] : 통합 라이브러리 연동 #145
  seat-service/build.gradle
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/application/service/SeatAdminService.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/application/service/SeatService.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/config/auditing/JpaAuditingConfig.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/config/auth/RedisUserInfoProvider.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/config/auth/WebMvcConfig.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/config/redis/RedisConfig.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/config/redis/RedissonConfig.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/domain/service/ProcessBlockSeatsService.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/presentation/controller/SeatController.java
Labels: ✏️ feat, 🛠️ refactor

#193 [Ticket] : 티켓 결제 완료 처리
  eureka-service/src/main/resources/db/migration/v35__alter_ticket.sql
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/application/user/TicketService.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/config/kafka/KafkaConsumerConfig.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/config/kafka/KafkaProducerConfig.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/domain/repository/TicketRepository.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/domain/service/RemoveTicketPaymentInfoService.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/infrastructure/adapter/kafka/PaymentEventConsumer.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/infrastructure/adapter/kafka/SeatEventConsumer.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/infrastructure/adapter/kafka/SeatKafkaProducer.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/infrastructure/adapter/kafka/dto/request/SeatListDto.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/infrastructure/adapter/kafka/dto/response/PaymentListenerDto.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/infrastructure/repository/TicketJpaRepository.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/infrastructure/repository/TicketRepositoryImpl.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/presentation/user/TicketController.java
Labels: ✏️ feat

#194 [Ticket] : 티켓 결제 완료 처리
  eureka-service/src/main/resources/db/migration/v35__alter_ticket.sql
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/application/user/TicketService.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/config/kafka/KafkaConsumerConfig.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/config/kafka/KafkaProducerConfig.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/domain/repository/TicketRepository.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/domain/service/RemoveTicketPaymentInfoService.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/infrastructure/adapter/kafka/PaymentEventConsumer.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/infrastructure/adapter/kafka/SeatEventConsumer.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/infrastructure/adapter/kafka/SeatKafkaProducer.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/infrastructure/adapter/kafka/dto/request/SeatListDto.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/infrastructure/adapter/kafka/dto/response/PaymentListenerDto.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/infrastructure/repository/TicketJpaRepository.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/infrastructure/repository/TicketRepositoryImpl.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/presentation/user/TicketController.java
Labels: ✏️ feat

#197 [Membership] 오류 수정
  membership-service/src/main/java/com/boeingmerryho/business/membershipservice/presentation/controller/feign/MembershipFeignController.java
Labels: 🔧 fix

#199 [Queue] : 대기열 서비스 redis, redisson 연결 오류 해결 및 코드 수정
  queue-service/src/main/java/com/boeingmerryho/business/queueservice/application/QueueHelper.java
  queue-service/src/main/java/com/boeingmerryho/business/queueservice/application/service/QueueFeignService.java
  queue-service/src/main/java/com/boeingmerryho/business/queueservice/application/service/QueueService.java
  queue-service/src/main/java/com/boeingmerryho/business/queueservice/config/RedisConfig.java
  queue-service/src/main/java/com/boeingmerryho/business/queueservice/config/RedissonConfig.java
  queue-service/src/main/java/com/boeingmerryho/business/queueservice/config/auth/WebMvcConfig.java
  queue-service/src/main/java/com/boeingmerryho/business/queueservice/exception/ErrorCode.java
  queue-service/src/main/java/com/boeingmerryho/business/queueservice/infrastructure/QueueHelperImpl.java
Labels: 🛠️ refactor, 🔧 fix

#209 [Gateway] : blacklist error handle add
  gateway-service/src/main/java/com/boeingmerryho/infrastructure/gatewayservice/filter/JwtAuthFilter.java
Labels: 🛠️ refactor

#212 [Seat] : 캐시된 좌석 자동 정리 #211
  eureka-service/src/main/resources/db/migration/V35__alter_match.sql
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/SeatServiceApplication.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/application/dto/request/ToTicketMatchDto.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/application/scheduler/AutoCleanCacheSeatsScheduler.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/domain/service/AutoCleanCacheSeatsService.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/domain/service/CreateCacheSeatsService.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/domain/service/ProcessBlockSeatsService.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/exception/SeatErrorCode.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/infrastructure/helper/MatchHelper.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/infrastructure/helper/SeatCommonHelper.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/infrastructure/reader/MatchReader.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/infrastructure/reader/MatchReaderImpl.java
Labels: ✏️ feat

#215 [Seat] : 캐시된 좌석 자동 추가 #214
  eureka-service/src/main/resources/db/migration/V35__alter_match.sql
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/SeatServiceApplication.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/application/dto/request/ToTicketMatchDto.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/application/scheduler/AutoCleanCacheSeatsScheduler.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/application/scheduler/AutoCreateCacheSeatsScheduler.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/domain/service/AutoCleanCacheSeatsService.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/domain/service/AutoCreateCacheSeatsService.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/domain/service/CreateCacheSeatsService.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/domain/service/ProcessBlockSeatsService.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/exception/SeatErrorCode.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/infrastructure/helper/MatchHelper.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/infrastructure/helper/SeatCommonHelper.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/infrastructure/reader/MatchReader.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/infrastructure/reader/MatchReaderImpl.java
Labels: ✏️ feat

#213 [Seat] : 캐시된 좌석 자동 정리 #211
  eureka-service/src/main/resources/db/migration/V35__alter_match.sql
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/SeatServiceApplication.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/application/dto/request/ToTicketMatchDto.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/application/scheduler/AutoCleanCacheSeatsScheduler.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/domain/service/AutoCleanCacheSeatsService.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/domain/service/CreateCacheSeatsService.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/domain/service/ProcessBlockSeatsService.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/exception/SeatErrorCode.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/infrastructure/helper/MatchHelper.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/infrastructure/helper/SeatCommonHelper.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/infrastructure/reader/MatchReader.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/infrastructure/reader/MatchReaderImpl.java
Labels: ✏️ feat

#221 [Seat] : 선예매 기능 구현하기 #220
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/application/service/SeatService.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/domain/Membership.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/domain/service/ProcessBlockSeatsService.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/exception/SeatErrorCode.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/infrastructure/helper/MembershipHelper.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/presentation/controller/SeatController.java
Labels: ✏️ feat, 🛠️ refactor

#223 [Payment] : 리팩토링, Factory 클래스 분리
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/application/dto/PaymentApplicationMapper.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/application/factory/KakaoPayRequestFactory.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/application/factory/PaymentSessionFactory.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/application/factory/PaymentStrategyFactory.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/application/service/PaySessionService.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/application/service/PaymentAdminService.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/application/service/PaymentFeignService.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/application/service/PaymentService.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/application/service/PaymentStrategy.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/domain/factory/PaymentFactory.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/domain/helper/PaymentReader.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/domain/repository/PaymentRepository.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/domain/type/DiscountType.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/domain/type/PaymentMethod.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/domain/type/PaymentType.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/infrastructure/helper/KafkaProducerHelper.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/infrastructure/helper/KakaoApiClient.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/infrastructure/helper/MembershipApiClient.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/infrastructure/helper/PaySessionHelper.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/infrastructure/kafka/producer/MembershipKafkaProducer.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/infrastructure/kafka/producer/TicketKafkaProducer.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/infrastructure/repository/PaymentMembershipJpaRepository.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/infrastructure/repository/PaymentRepositoryImpl.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/infrastructure/repository/PaymentTicketJpaRepository.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/infrastructure/service/BankTransferStrategy.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/infrastructure/service/KakaoPayStrategy.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/infrastructure/service/PaySessionServiceImpl.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/infrastructure/service/PaymentAdminServiceImpl.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/infrastructure/service/PaymentFeignServiceImpl.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/infrastructure/service/PaymentServiceImpl.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/presentation/code/PaymentErrorCode.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/presentation/code/PaymentSuccessCode.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/presentation/controller/PaymentAdminController.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/presentation/controller/PaymentController.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/presentation/controller/PaymentFeignController.java
Labels: ✏️ feat, 🛠️ refactor

#224 [Payment] : 리팩토링, Factory 클래스 분리
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/application/dto/PaymentApplicationMapper.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/application/factory/KakaoPayRequestFactory.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/application/factory/PaymentSessionFactory.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/application/factory/PaymentStrategyFactory.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/application/service/PaySessionService.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/application/service/PaymentAdminService.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/application/service/PaymentFeignService.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/application/service/PaymentService.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/application/service/PaymentStrategy.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/domain/factory/PaymentFactory.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/domain/helper/PaymentReader.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/domain/repository/PaymentRepository.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/domain/type/DiscountType.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/domain/type/PaymentMethod.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/domain/type/PaymentType.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/infrastructure/helper/KafkaProducerHelper.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/infrastructure/helper/KakaoApiClient.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/infrastructure/helper/MembershipApiClient.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/infrastructure/helper/PaySessionHelper.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/infrastructure/kafka/producer/MembershipKafkaProducer.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/infrastructure/kafka/producer/TicketKafkaProducer.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/infrastructure/repository/PaymentMembershipJpaRepository.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/infrastructure/repository/PaymentRepositoryImpl.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/infrastructure/repository/PaymentTicketJpaRepository.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/infrastructure/service/BankTransferStrategy.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/infrastructure/service/KakaoPayStrategy.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/infrastructure/service/PaySessionServiceImpl.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/infrastructure/service/PaymentAdminServiceImpl.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/infrastructure/service/PaymentFeignServiceImpl.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/infrastructure/service/PaymentServiceImpl.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/presentation/code/PaymentErrorCode.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/presentation/code/PaymentSuccessCode.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/presentation/controller/PaymentAdminController.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/presentation/controller/PaymentController.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/presentation/controller/PaymentFeignController.java
Labels: ✏️ feat, 🛠️ refactor

#226 [Queue] : 동시성 테스트 추가
  queue-service/build.gradle
  queue-service/src/main/java/com/boeingmerryho/business/queueservice/exception/ErrorCode.java
  queue-service/src/test/java/com/boeingmerryho/business/queueservice/application/QueueServiceConcurrencyTest.java
Labels: 📑 test

#233 [Ticket] : 티켓 서비스 리팩토링
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/application/feign/dto/response/PaymentCreationResponseDto.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/application/user/TicketPaymentEventService.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/application/user/TicketSeatEventService.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/application/user/TicketService.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/config/ResilienceConfig.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/domain/PaymentStatus.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/domain/TicketPaymentResult.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/domain/repository/TicketPaymentRepository.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/domain/service/RemoveTicketPaymentInfoService.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/domain/service/TicketFactory.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/domain/service/TicketStatusUpdateService.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/exception/ErrorCode.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/infrastructure/adapter/kafka/PaymentEventConsumer.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/infrastructure/adapter/kafka/SeatEventConsumer.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/infrastructure/adapter/kafka/dto/response/PaymentListenerDto.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/infrastructure/repository/TicketPaymentRedisRepository.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/infrastructure/service/TicketPaymentServiceImpl.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/infrastructure/service/feign/PaymentClient.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/infrastructure/service/feign/QueueClient.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/infrastructure/service/feign/dto/request/IssuedTicketDto.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/infrastructure/service/feign/dto/request/PaymentCreationRequestDto.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/infrastructure/service/feign/dto/response/PaymentCreationResponseDto.java
  ticket-service/src/test/java/com/boeingmerryho/business/ticketservice/application/admin/AdminTicketServiceTest.java
Labels: 🛠️ refactor

#232 [Store] : 1차 리팩토링
  membership-service/src/main/java/com/boeingmerryho/business/membershipservice/exception/GlobalExceptionHandler.java
  membership-service/src/main/java/com/boeingmerryho/business/membershipservice/infrastructure/helper/MembershipRedisHelper.java
  membership-service/src/main/java/com/boeingmerryho/business/membershipservice/presentation/controller/user/MembershipController.java
  membership-service/src/main/java/com/boeingmerryho/business/membershipservice/presentation/controller/user/MembershipUserController.java
  store-service/src/main/java/com/boeingmerryho/business/storeservice/application/service/StoreAdminService.java
  store-service/src/main/java/com/boeingmerryho/business/storeservice/application/service/command/CloseStoreCommand.java
  store-service/src/main/java/com/boeingmerryho/business/storeservice/application/service/command/OpenStoreCommand.java
  store-service/src/main/java/com/boeingmerryho/business/storeservice/application/service/command/StoreCommand.java
  store-service/src/main/java/com/boeingmerryho/business/storeservice/application/service/command/StoreCommandFactory.java
  store-service/src/main/java/com/boeingmerryho/business/storeservice/application/service/command/StoreCommandType.java
  store-service/src/main/java/com/boeingmerryho/business/storeservice/domain/service/StoreDomainService.java
  store-service/src/main/java/com/boeingmerryho/business/storeservice/exception/StoreErrorCode.java
  store-service/src/main/java/com/boeingmerryho/business/storeservice/infrastructure/config/RedisConfig.java
  store-service/src/main/java/com/boeingmerryho/business/storeservice/infrastructure/helper/StoreAdminHelper.java
  store-service/src/main/java/com/boeingmerryho/business/storeservice/infrastructure/scheduler/RedisZSetDelayQueuePoller.java
  store-service/src/main/java/com/boeingmerryho/business/storeservice/infrastructure/scheduler/StoreDailyQueueScheduler.java
  store-service/src/main/java/com/boeingmerryho/business/storeservice/presentation/StoreSuccessCode.java
  store-service/src/main/java/com/boeingmerryho/business/storeservice/presentation/controller/StoreAdminController.java
Labels: 🛠️ refactor

#234 [Ticket] : 티켓 서비스 리팩토링
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/application/feign/dto/response/PaymentCreationResponseDto.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/application/user/TicketPaymentEventService.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/application/user/TicketSeatEventService.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/application/user/TicketService.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/config/ResilienceConfig.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/domain/PaymentStatus.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/domain/TicketPaymentResult.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/domain/repository/TicketPaymentRepository.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/domain/service/RemoveTicketPaymentInfoService.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/domain/service/TicketFactory.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/domain/service/TicketStatusUpdateService.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/exception/ErrorCode.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/infrastructure/adapter/kafka/PaymentEventConsumer.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/infrastructure/adapter/kafka/SeatEventConsumer.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/infrastructure/adapter/kafka/dto/response/PaymentListenerDto.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/infrastructure/repository/TicketPaymentRedisRepository.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/infrastructure/service/TicketPaymentServiceImpl.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/infrastructure/service/feign/PaymentClient.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/infrastructure/service/feign/QueueClient.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/infrastructure/service/feign/dto/request/IssuedTicketDto.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/infrastructure/service/feign/dto/request/PaymentCreationRequestDto.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/infrastructure/service/feign/dto/response/PaymentCreationResponseDto.java
  ticket-service/src/test/java/com/boeingmerryho/business/ticketservice/application/admin/AdminTicketServiceTest.java
Labels: 🛠️ refactor, 🔧 fix

#248 [Seat] : 멤버십 기능 추가 #247
  eureka-service/src/main/resources/db/migration/V36__alter_seat.sql
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/application/service/SeatService.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/domain/Seat.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/domain/service/CreateCacheSeatsService.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/exception/SeatErrorCode.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/infrastructure/helper/MembershipHelper.java
Labels: ✏️ feat

#249 [Seat] : 멤버십 기능 추가 #247
  eureka-service/src/main/resources/db/migration/V36__alter_seat.sql
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/application/service/SeatService.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/domain/Seat.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/domain/service/CreateCacheSeatsService.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/exception/SeatErrorCode.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/infrastructure/helper/MembershipHelper.java
Labels: ✏️ feat

#252 [Membership] 도커 파일 생성
  membership-service/Dockerfile
Labels: ✏️ feat

#257 [Seat] : 좌석 생성 로직 수정 #256
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/config/redis/RedissonConfig.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/domain/service/CreateCacheSeatsService.java
Labels: 🛠️ refactor

#258 [Seat] : 좌석 생성 로직 수정 #256
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/config/redis/RedissonConfig.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/domain/service/CreateCacheSeatsService.java
Labels: 🛠️ refactor

#260 [Seat] : 블록 별 좌석 조회하기 로직 수정 #259
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/application/service/SeatService.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/domain/service/GetCacheBlockSeatsService.java
Labels: 🛠️ refactor

#261 [Seat] : 블록 별 좌석 조회하기 로직 수정 #259
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/application/service/SeatService.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/domain/service/GetCacheBlockSeatsService.java
Labels: 🛠️ refactor

#262 feat: payment - logback 설정#250
  payment-service/src/main/resources/logback-spring.xml
Labels: ✏️ feat

#266 feat: service - profile 모드 변경#250
  user-service/src/main/resources/application.yml
Labels: ✏️ feat

#264 [Payment] : logback 설정, log 파일
  eureka-service/src/main/resources/application.yml
  gateway-service/src/main/resources/application.yml
  membership-service/src/main/resources/application.yml
  payment-service/src/main/resources/logback-spring.xml
  queue-service/src/main/resources/application.yml
  seat-service/src/main/resources/application.yaml
  store-service/src/main/resources/application.yml
  ticket-service/src/main/resources/application.yml
  user-service/src/main/resources/application.yml
Labels: ✏️ feat

#267 [Ticket] : resilience4J 의존성 추가
  ticket-service/build.gradle
Labels: 🔧 fix

#270 [Seat] : 좌석 선점하기 로직 수정 #269
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/application/service/KafkaListenerService.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/application/service/KafkaProducerService.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/application/service/SeatService.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/domain/service/ProcessBlockSeatsService.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/exception/MembershipErrorCode.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/infrastructure/adaptor/kafka/listener/SeatFailedListener.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/infrastructure/adaptor/kafka/listener/SeatSucceedListener.java
Labels: 🛠️ refactor

#268 [Ticket] : resilience4J 의존성 추가
  ticket-service/build.gradle
Labels: 🔧 fix

#276 [Seat] : 도메인 서비스 로직 수정 #275
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/domain/service/AutoCleanCacheSeatsService.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/domain/service/CreateCacheSeatsService.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/domain/service/ProcessBlockSeatsService.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/domain/service/SeatFailedService.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/domain/service/SeatSucceedService.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/infrastructure/helper/SeatListenerHelper.java
Labels: 🛠️ refactor

#277 [Seat] : 도메인 서비스 로직 수정 #275
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/domain/service/AutoCleanCacheSeatsService.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/domain/service/CreateCacheSeatsService.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/domain/service/ProcessBlockSeatsService.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/domain/service/SeatFailedService.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/domain/service/SeatSucceedService.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/infrastructure/helper/SeatListenerHelper.java
Labels: 🛠️ refactor

#282 [Payment] : logging 설정
  payment-service/src/main/resources/logback-spring.xml
Labels: ⚙️ setting

#279 [Gateway] : logback 설정
  gateway-service/build.gradle
  gateway-service/src/main/java/com/boeingmerryho/infrastructure/gatewayservice/exception/JwtErrorCode.java
  gateway-service/src/main/java/com/boeingmerryho/infrastructure/gatewayservice/exception/RateLimitErrorCode.java
  gateway-service/src/main/java/com/boeingmerryho/infrastructure/gatewayservice/filter/GlobalGatewayFilter.java
  gateway-service/src/main/java/com/boeingmerryho/infrastructure/gatewayservice/filter/JwtAuthFilter.java
  gateway-service/src/main/java/com/boeingmerryho/infrastructure/gatewayservice/filter/util/IpKeyResolver.java
  gateway-service/src/main/resources/logback-spring.xml
Labels: ✏️ feat

#290 [Seat] : GCP Logback 설정
  seat-service/build.gradle
  seat-service/src/main/resources/logback.xml
Labels: 🛠️ refactor

#307 [Ticket] : 티켓 서비스 Metric 및 로그 설정
  ticket-service/build.gradle
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/config/MetricConfig.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/config/Resilience4JRetryConfig.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/config/ResilienceConfig.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/config/auth/WebMvcConfig.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/infrastructure/adapter/kafka/SeatEventConsumer.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/infrastructure/service/TicketPaymentServiceImpl.java
  ticket-service/src/main/resources/logback-spring.xml
Labels: ✏️ feat

#302 [Seat] : 메트릭 설정하기 #297
  seat-service/build.gradle
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/config/auth/WebMvcConfig.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/config/metric/MetricConfig.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/presentation/controller/SeatController.java
Labels: ⚙️ setting

#306 [Payment] : metrics 설정
  payment-service/build.gradle
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/infrastructure/config/MetricConfig.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/infrastructure/config/auth/WebMvcConfig.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/infrastructure/service/BankTransferStrategy.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/infrastructure/service/KakaoPayStrategy.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/infrastructure/service/PaymentServiceImpl.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/presentation/controller/PaymentAdminController.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/presentation/controller/PaymentController.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/presentation/controller/PaymentFeignController.java
  payment-service/src/main/resources/logback-spring.xml
Labels: ✏️ feat

#308 [Ticket] : 티켓 서비스 Metric 및 로그 설정/적용
  ticket-service/build.gradle
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/config/MetricConfig.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/config/Resilience4JRetryConfig.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/config/ResilienceConfig.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/config/auth/WebMvcConfig.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/infrastructure/adapter/kafka/SeatEventConsumer.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/infrastructure/service/TicketPaymentServiceImpl.java
  ticket-service/src/main/resources/logback-spring.xml
Labels: ✏️ feat, ⚙️ setting

#311 [Gateway] : metric 수집 추가
  gateway-service/build.gradle
  gateway-service/src/main/java/com/boeingmerryho/infrastructure/gatewayservice/config/MetricConfig.java
  gateway-service/src/main/java/com/boeingmerryho/infrastructure/gatewayservice/filter/GlobalGatewayFilter.java
Labels: ✏️ feat, ⚙️ setting

#314 [Store] : store 메트릭 설정
  store-service/build.gradle
  store-service/src/main/java/com/boeingmerryho/business/storeservice/infrastructure/config/TimedConfig.java
  store-service/src/main/java/com/boeingmerryho/business/storeservice/infrastructure/scheduler/RedisZSetDelayQueuePoller.java
  store-service/src/main/java/com/boeingmerryho/business/storeservice/infrastructure/scheduler/StoreDailyQueueScheduler.java
Labels: ⚙️ setting

#321 [User] : 이벤트 처리 추가 및 로깅 protobuf 의존성 추가
  gateway-service/build.gradle
  membership-service/build.gradle
  payment-service/build.gradle
  queue-service/build.gradle
  queue-service/src/main/java/com/boeingmerryho/business/queueservice/application/service/QueueAdminService.java
  queue-service/src/main/java/com/boeingmerryho/business/queueservice/application/service/QueueService.java
  queue-service/src/main/java/com/boeingmerryho/business/queueservice/config/MetricConfig.java
  queue-service/src/main/java/com/boeingmerryho/business/queueservice/config/auth/WebMvcConfig.java
  queue-service/src/main/java/com/boeingmerryho/business/queueservice/infrastructure/QueueMetricsHelperImpl.java
  seat-service/build.gradle
  store-service/build.gradle
  ticket-service/build.gradle
  user-service/build.gradle
  user-service/src/main/java/com/boeingmerryho/business/userservice/application/service/UserAdminService.java
  user-service/src/main/java/com/boeingmerryho/business/userservice/application/service/UserService.java
  user-service/src/main/java/com/boeingmerryho/business/userservice/domain/event/UserLoginFailureEvent.java
  user-service/src/main/java/com/boeingmerryho/business/userservice/domain/event/UserLoginSuccessEvent.java
  user-service/src/main/java/com/boeingmerryho/business/userservice/domain/event/UserWithdrawEvent.java
  user-service/src/main/java/com/boeingmerryho/business/userservice/infrastructure/event/UserLoginEventListener.java
  user-service/src/main/java/com/boeingmerryho/business/userservice/infrastructure/event/UserWithdrawEventListener.java
Labels: ✏️ feat, 🛠️ refactor, ⚙️ setting

#326 [All] : TimeZone 설정하기 #325
  config-service/src/main/java/com/boeingmerryho/infrastructure/config_service/ConfigServiceApplication.java
  eureka-service/src/main/java/com/boeingmerryho/infrastructure/eurekaservice/EurekaServiceApplication.java
  gateway-service/src/main/java/com/boeingmerryho/infrastructure/gatewayservice/GatewayServiceApplication.java
  membership-service/src/main/java/com/boeingmerryho/business/membershipservice/MembershipServiceApplication.java
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/PaymentServiceApplication.java
  queue-service/src/main/java/com/boeingmerryho/business/queueservice/QueueServiceApplication.java
  seat-service/src/main/java/com/boeingmerryho/business/seatservice/SeatServiceApplication.java
  store-service/src/main/java/com/boeingmerryho/business/storeservice/StoreServiceApplication.java
  ticket-service/src/main/java/com/boeingmerryho/business/ticketservice/TicketServiceApplication.java
  user-service/src/main/java/com/boeingmerryho/business/userservice/UserServiceApplication.java
Labels: ⚙️ setting

#328 [All] : Flyway 파일 정리 #327
  eureka-service/src/main/resources/db/migration/V10__create_seat.sql
  eureka-service/src/main/resources/db/migration/V11__create_seat_reservation.sql
  eureka-service/src/main/resources/db/migration/V12__create_payment.sql
  eureka-service/src/main/resources/db/migration/V13__create_detail.sql
  eureka-service/src/main/resources/db/migration/V13__create_payment_detail.sql
  eureka-service/src/main/resources/db/migration/V14__create_payment_ticket.sql
  eureka-service/src/main/resources/db/migration/V15__create_payment_membership.sql
  eureka-service/src/main/resources/db/migration/V16__create_store.sql
  eureka-service/src/main/resources/db/migration/V17__create_queue.sql
  eureka-service/src/main/resources/db/migration/V18__create_notification.sql
  eureka-service/src/main/resources/db/migration/V19__insert_membership_sample_data.sql
  eureka-service/src/main/resources/db/migration/V19__insert_user.sql
  eureka-service/src/main/resources/db/migration/V20__insert_membership.sql
  eureka-service/src/main/resources/db/migration/V20__insert_shop_sample_data.sql
  eureka-service/src/main/resources/db/migration/V21__insert_membership_user.sql
  eureka-service/src/main/resources/db/migration/V21__insert_team_sample_data.sql
  eureka-service/src/main/resources/db/migration/V22__insert_stadium.sql
  eureka-service/src/main/resources/db/migration/V22__insert_stadium_sample_data.sql
  eureka-service/src/main/resources/db/migration/V23__insert_match_sample_data.sql
  eureka-service/src/main/resources/db/migration/V23__insert_team.sql
  eureka-service/src/main/resources/db/migration/V24__insert_match.sql
  eureka-service/src/main/resources/db/migration/V24__insert_user_sample_data.sql
  eureka-service/src/main/resources/db/migration/V25__insert_queue_sample_data.sql
  eureka-service/src/main/resources/db/migration/V25__insert_seat.sql
  eureka-service/src/main/resources/db/migration/V26__alter_detail.sql
  eureka-service/src/main/resources/db/migration/V26__insert_seat_sample_data.sql
  eureka-service/src/main/resources/db/migration/V27__alter_detail.sql
  eureka-service/src/main/resources/db/migration/V28__alter_payment.sql
  eureka-service/src/main/resources/db/migration/V29__create_partitioned_membership_user.sql
  eureka-service/src/main/resources/db/migration/V2__create_user.sql
  eureka-service/src/main/resources/db/migration/V30__alter_membership.sql
  eureka-service/src/main/resources/db/migration/V31__alter_membership.sql
  eureka-service/src/main/resources/db/migration/V32__alter_payment.sql
  eureka-service/src/main/resources/db/migration/V33__alter_queue.sql
  eureka-service/src/main/resources/db/migration/V34__alter_payment_membership.sql
  eureka-service/src/main/resources/db/migration/V35__alter_match.sql
  eureka-service/src/main/resources/db/migration/V36__alter_seat.sql
  eureka-service/src/main/resources/db/migration/V3__create_membership.sql
  eureka-service/src/main/resources/db/migration/V4__create_membership_user.sql
  eureka-service/src/main/resources/db/migration/V5__create_ticket.sql
  eureka-service/src/main/resources/db/migration/V6__create_ticket_history.sql
  eureka-service/src/main/resources/db/migration/V7__create_match.sql
  eureka-service/src/main/resources/db/migration/V8__create_stadium.sql
  eureka-service/src/main/resources/db/migration/V9__create_team.sql
Labels: 🛠️ refactor

#330 [Eureka] : flyway
  eureka-service/src/main/resources/application.yml
  eureka-service/src/main/resources/db/migration/V13__create_payment_detail.sql
  eureka-service/src/main/resources/db/migration/V27__apply_match_index.sql
  eureka-service/src/main/resources/db/migration/V28__apply_ticket_index.sql
  eureka-service/src/main/resources/db/migration/V29__apply_payment_index.sql
  eureka-service/src/main/resources/db/migration/V30__apply_user_index.sql
  eureka-service/src/main/resources/db/migration/V4__create_membership_user.sql
Labels: ✏️ feat

#332 [Membership] 멤버십 선점 리팩토링
  membership-service/src/main/java/com/boeingmerryho/business/membershipservice/application/service/kafka/ListenerService.java
  membership-service/src/main/java/com/boeingmerryho/business/membershipservice/infrastructure/config/KafkaConsumerConfig.java
  membership-service/src/main/java/com/boeingmerryho/business/membershipservice/infrastructure/config/RedisConfig.java
  membership-service/src/main/java/com/boeingmerryho/business/membershipservice/infrastructure/helper/MembershipListenerHelper.java
  membership-service/src/main/java/com/boeingmerryho/business/membershipservice/infrastructure/helper/MembershipRedisHelper.java
  membership-service/src/main/java/com/boeingmerryho/business/membershipservice/infrastructure/kafka/consumer/MembershipRollbackConsumer.java
  membership-service/src/main/java/com/boeingmerryho/business/membershipservice/infrastructure/kafka/listener/PaymentSuccessKafkaListener.java
  membership-service/src/main/java/com/boeingmerryho/business/membershipservice/infrastructure/kafka/listener/RedisExpirationListener.java
Labels: 🛠️ refactor

#334 [Payment] : 결제 유효 시간 검증 로직
  payment-service/src/main/java/com/boeingmerryho/business/paymentservice/infrastructure/service/PaymentServiceImpl.java
Labels: 🛠️ refactor
